### ISSUE TITLE
Allow for custom subdomains

### ISSUE THREAD

**Issue by xori** [Twixes/backname#2]
`site-1.127.0.0.1.backname.io` doesn't seem to resolve to `127.0.0.1` like I'd expect.

This would be useful for virtual host config setups, so devs (and myself) wouldn't have to modify our host files when we want to develop multiple sites at the same time.

- `site-1.0--1.backname.io`
- `site-2.0--1.backname.io`

All resolving to `::1` would also be super handy (and short!) url options.

**Comment by Twixes** [comment]
Good point, that's a use case I missed. Will add support for this.
